controllers:
    resource: ../src/Controller/
    type: attribute

api_login_check:
    path: /api/login_check

my_route:
    path: /v1/foo/route
    condition: "request.attributes.get('version') == 'v1'"